"""pagos por venta e items varios

Revision ID: af146e38f60e
Revises: 8311a5d866a1
Create Date: 2026-09-30 19:40:00.810334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af146e38f60e'
down_revision: Union[str, Sequence[str], None] = '8311a5d866a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('medio', sa.Enum('efectivo', 'debito', 'credito', 'transferencia', 'qr', name='mediopago', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('monto', sa.BigInteger(), nullable=False),
    sa.Column('recibido', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('monto > 0', name=op.f('ck_venta_pagos_monto_positivo')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_venta_pagos_venta_id_ventas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_pagos'))
    )
    op.create_index(op.f('ix_venta_pagos_venta_id'), 'venta_pagos', ['venta_id'], unique=False)
    op.alter_column('venta_items', 'producto_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('ventas', 'medio_pago')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('medio_pago', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('venta_items', 'producto_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_venta_pagos_venta_id'), table_name='venta_pagos')
    op.drop_table('venta_pagos')
    # ### end Alembic commands ###
