"""modelo inicial

Revision ID: 8311a5d866a1
Revises: 
Create Date: 2026-09-30 12:51:08.963824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8311a5d866a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kioskos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kioskos'))
    )
    op.create_table('cajas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kiosko_id', sa.Uuid(), nullable=False),
    sa.Column('abierta_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monto_inicial', sa.BigInteger(), nullable=False),
    sa.Column('monto_contado', sa.BigInteger(), nullable=True),
    sa.Column('nota', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_cajas_kiosko_id_kioskos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cajas'))
    )
    op.create_index('uq_cajas_una_abierta_por_kiosko', 'cajas', ['kiosko_id'], unique=True, postgresql_where=sa.text('cerrada_en IS NULL'))
    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kiosko_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=64), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio_venta', sa.BigInteger(), nullable=False),
    sa.Column('costo', sa.BigInteger(), nullable=True),
    sa.Column('unidad', sa.Enum('unidad', 'kg', name='unidad', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio_venta >= 0', name=op.f('ck_productos_precio_no_negativo')),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_productos_kiosko_id_kioskos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos'))
    )
    op.create_index(op.f('ix_productos_kiosko_id'), 'productos', ['kiosko_id'], unique=False)
    op.create_index('uq_productos_kiosko_codigo', 'productos', ['kiosko_id', 'codigo_barras'], unique=True, postgresql_where=sa.text('codigo_barras IS NOT NULL'))
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kiosko_id', sa.Uuid(), nullable=False),
    sa.Column('caja_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipomovimientocaja', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('monto', sa.BigInteger(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_movimientos_caja_monto_positivo')),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], name=op.f('fk_movimientos_caja_caja_id_cajas')),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_movimientos_caja_kiosko_id_kioskos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_caja'))
    )
    op.create_index(op.f('ix_movimientos_caja_caja_id'), 'movimientos_caja', ['caja_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kiosko_id', sa.Uuid(), nullable=False),
    sa.Column('caja_id', sa.Uuid(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('medio_pago', sa.Enum('efectivo', 'debito', 'credito', 'transferencia', 'qr', name='mediopago', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], name=op.f('fk_ventas_caja_id_cajas')),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_ventas_kiosko_id_kioskos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas'))
    )
    op.create_index(op.f('ix_ventas_caja_id'), 'ventas', ['caja_id'], unique=False)
    op.create_index('ix_ventas_kiosko_fecha', 'ventas', ['kiosko_id', 'creado_en'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kiosko_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.Enum('compra', 'venta', 'ajuste', 'merma', name='motivostock', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_movimientos_stock_kiosko_id_kioskos')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_movimientos_stock_producto_id_productos')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_movimientos_stock_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_stock'))
    )
    op.create_index(op.f('ix_movimientos_stock_producto_id'), 'movimientos_stock', ['producto_id'], unique=False)
    op.create_table('venta_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio_unitario', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_venta_items_producto_id_productos')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_venta_items_venta_id_ventas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_items'))
    )
    op.create_index(op.f('ix_venta_items_venta_id'), 'venta_items', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_items_venta_id'), table_name='venta_items')
    op.drop_table('venta_items')
    op.drop_index(op.f('ix_movimientos_stock_producto_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index('ix_ventas_kiosko_fecha', table_name='ventas')
    op.drop_index(op.f('ix_ventas_caja_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_movimientos_caja_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index('uq_productos_kiosko_codigo', table_name='productos', postgresql_where=sa.text('codigo_barras IS NOT NULL'))
    op.drop_index(op.f('ix_productos_kiosko_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index('uq_cajas_una_abierta_por_kiosko', table_name='cajas', postgresql_where=sa.text('cerrada_en IS NULL'))
    op.drop_table('cajas')
    op.drop_table('kioskos')
    # ### end Alembic commands ###
